/**
 * Server-side FiveM resource builder for pack revisions.
 *
 * PROVENANCE: originally ported from creative/lib/server/cloth-export.ts and
 * creative/lib/server/cloth-shop-meta.ts; since Phase 3 this file is a 1:1
 * mirror of the DESKTOP sidecar builder (atelier/sidecar/Engine/Build/
 * BuildPlanner.cs + ShopMetaGenerator.cs + Targets/FivemBuilder.cs) — the
 * sidecar is the canonical implementation because it pairs the stream files
 * with the real binary YMTs. Every text artifact that exists in BOTH builds
 * (stream names, shop_ped_apparel*.meta, fxmanifest.lua) must stay
 * BYTE-IDENTICAL ("\n" line endings, UTF-8 without BOM).
 *
 * ============================ SERVER BUILD LIMITATION =====================
 * The REAL binary CPedVariationInfo .ymt files (mp_m_freemode_01_<dlc>.ymt /
 * mp_f_freemode_01_<dlc>.ymt) and mp_creaturemetadata_<m|f>_<dlc>.ymt can
 * only be generated by CodeWalker.Core (.NET) — i.e. by the DESKTOP sidecar
 * build. This server build ships everything EXCEPT the .ymt files and puts
 * a clearly documented placeholder note into stream/ATELIER_README.txt;
 * atelier-build.json carries "ymt": "missing-server-build". Registry
 * downloads therefore work for previewing/distribution, full in-game packs
 * come from desktop builds. A future ymt-service sidecar deployment can
 * close the gap.
 * ==========================================================================
 *
 * Stream naming (mirror of sidecar StreamNames; props KEEP their p_ slot
 * prefix — the game resolves prop drawables as p_<anchor>_NNN):
 *   component: <ped>_<dlc>^<slot>_<NNN>_u.ydd
 *              <ped>_<dlc>^<slot>_diff_<NNN>_<letter>_uni.ytd
 *   prop:      <ped>_p_<dlc>^<slot>_<NNN>.ydd            (slot e.g. p_head)
 *              <ped>_p_<dlc>^<slot>_diff_<NNN>_<letter>.ytd
 *   physics:   same base name as the .ydd with extension .yld
 *   replace:   no dlc in the prefix (<ped>^<slot>_<NNN>_u.ydd) — the file
 *              overrides the base-game asset; NNN = replaceTargetId
 * with <ped> = mp_m_freemode_01 | mp_f_freemode_01 and NNN = the DERIVED
 * drawableId (3 digits) = index within the (part, gender, slot) bucket.
 *
 * SPLIT SEMANTICS (mirror of sidecar BuildPlanner):
 *   1. Per gender, the ADDON drawables are taken in revision order as one
 *      flat list and chunked into groups of `splitAt` (default 128).
 *   2. Part k contains chunk k of the male list plus chunk k of the female
 *      list; the number of parts is the max chunk count over both genders.
 *      No (gender, slot) bucket inside one part can exceed splitAt — the
 *      game-side limit of 128 drawables per (dlc, gender, slot).
 *   3. With more than one part, EVERY part gets the suffix _part<N> (1-based)
 *      on both the resource folder and the dlcName.
 *   4. Stream NNN numbering restarts per (part, gender, slot), so each part
 *      is a complete, self-contained DLC whose names line up with its own
 *      (desktop-built) YMTs.
 *   5. Replace-mode drawables never enter a YMT or shop meta; they ride in
 *      part 1 as base-name override files with NNN = replaceTargetId.
 */

import JSZip from "jszip";
import type { RevisionDrawable } from "../models/atelierRevision";

export const DEFAULT_SPLIT_AT = 128;

export interface FivemBuildOptions {
  dlcName: string;
  resourceName: string;
  /** default true */
  generateShopMeta?: boolean;
  /** max drawables per (gender, slot) bucket per resource part, default 128 */
  splitAt?: number;
  /**
   * Optional fxmanifest override from the admin build-config. When set, the
   * fxmanifest.lua is rendered from this template (placeholders {{data_files}}
   * and {{files}} are substituted per part) instead of the default. UNSET keeps
   * the byte-identical default manifest (mirror of the desktop build) — the
   * override is strictly opt-in so untouched packs never diverge.
   */
  fxmanifestTemplate?: string;
}

/** Resolve a CAS asset to its bytes; null = missing on disk. */
export type CasAssetReader = (sha256: string) => Promise<Uint8Array | null>;

export interface FivemBuildReport {
  resources: { folder: string; drawables: number }[];
  warnings: string[];
}

/** Mirror of sidecar GtaSlots.ComponentIds (pack.atelier "type" -> componentId). */
const COMPONENT_IDS: Record<string, number> = {
  head: 0, berd: 1, hair: 2, uppr: 3, lowr: 4, hand: 5,
  feet: 6, teef: 7, accs: 8, task: 9, decl: 10, jbib: 11,
};

/** Mirror of sidecar GtaSlots.CompNativeNames (shop meta eCompType by componentId). */
const COMP_NATIVE_NAMES = [
  "PV_COMP_HEAD", "PV_COMP_BERD", "PV_COMP_HAIR", "PV_COMP_UPPR", "PV_COMP_LOWR", "PV_COMP_HAND",
  "PV_COMP_FEET", "PV_COMP_TEEF", "PV_COMP_ACCS", "PV_COMP_TASK", "PV_COMP_DECL", "PV_COMP_JBIB",
] as const;

export function sanitizeDlcName(raw: string): string {
  return raw.replace(/[^a-zA-Z0-9_]/gu, "_").toLowerCase() || "atelier_pack";
}

export function sanitizeResourceName(raw: string): string {
  return raw.replace(/[^a-zA-Z0-9_-]/gu, "_") || "atelier_pack";
}

function pedName(gender: "male" | "female"): string {
  return gender === "male" ? "mp_m_freemode_01" : "mp_f_freemode_01";
}

function genderLetter(gender: "male" | "female"): "m" | "f" {
  return gender === "male" ? "m" : "f";
}

function pad3(n: number): string {
  return String(n).padStart(3, "0");
}

/** Texture letter by array position: 0 -> a, 1 -> b, ... (mirror of StreamNames.TextureLetter). */
function textureLetter(index: number): string {
  return String.fromCharCode("a".charCodeAt(0) + (index % 26));
}

/** Stream-name prefix: ped (+_p for props) (+_dlc unless replace). */
function streamPrefix(d: RevisionDrawable, dlc: string | null): string {
  const ped = d.kind === "prop" ? `${pedName(d.gender)}_p` : pedName(d.gender);
  return dlc === null ? ped : `${ped}_${dlc}`;
}

/** .ydd stream name; dlc = null for replace-mode base-name overrides. */
export function drawableStreamBase(d: RevisionDrawable, dlc: string | null, nnn: number): string {
  const inner = d.kind === "prop" ? `${d.type}_${pad3(nnn)}` : `${d.type}_${pad3(nnn)}_u`;
  return `${streamPrefix(d, dlc)}^${inner}`;
}

/** Stream name of texture letter `i` for a drawable. */
export function textureStreamName(d: RevisionDrawable, dlc: string | null, nnn: number, i: number): string {
  const inner = d.kind === "prop"
    ? `${d.type}_diff_${pad3(nnn)}_${textureLetter(i)}`
    : `${d.type}_diff_${pad3(nnn)}_${textureLetter(i)}_uni`;
  return `${streamPrefix(d, dlc)}^${inner}.ytd`;
}

/** .yld stream name (components only; mirror of StreamNames.Yld). */
function physicsStreamName(d: RevisionDrawable, dlc: string | null, nnn: number): string {
  return `${streamPrefix(d, dlc)}^${d.type}_${pad3(nnn)}_u.yld`;
}

/** Mirror of .NET SecurityElement.Escape (used by the sidecar generators). */
function xmlEscape(s: string): string {
  return s
    .replace(/&/gu, "&amp;")
    .replace(/</gu, "&lt;")
    .replace(/>/gu, "&gt;")
    .replace(/"/gu, "&quot;")
    .replace(/'/gu, "&apos;");
}

/**
 * fxmanifest.lua — byte-identical mirror of sidecar FivemBuilder
 * .BuildFxManifest (the first-person block never triggers server-side
 * because first-person variants are not exported here).
 */
function buildFxmanifest(shopMetaFiles: string[]): string {
  const lines = [
    "fx_version 'cerulean'",
    "game 'gta5'",
    "",
    "files {",
    "  'stream/*.ydd',",
    "  'stream/*.ytd',",
    "  'stream/*.yld',",
    "  'stream/*.meta',",
    "  'stream/*.ymt'",
    "}",
    "",
  ];
  for (const metaFile of shopMetaFiles) {
    lines.push(`data_file 'SHOP_PED_APPAREL_META_FILE' '${metaFile}'`);
  }
  return `${lines.join("\n")}\n`;
}

/** The default fxmanifest as an editable template — shown in the admin editor. */
export const DEFAULT_FXMANIFEST_TEMPLATE = `fx_version 'cerulean'
game 'gta5'

files {
{{files}}
}

{{data_files}}`;

const FILES_BLOCK = [
  "  'stream/*.ydd',",
  "  'stream/*.ytd',",
  "  'stream/*.yld',",
  "  'stream/*.meta',",
  "  'stream/*.ymt'",
].join("\n");

/**
 * Render an admin-provided fxmanifest template. Substitutes {{files}} (the
 * streamed-asset globs) and {{data_files}} (one shop-meta data_file line per
 * part-gender) and guarantees a trailing newline. Used ONLY when a pack has a
 * custom template configured — see FivemBuildOptions.fxmanifestTemplate.
 */
export function renderFxmanifestTemplate(template: string, shopMetaFiles: string[]): string {
  const dataFiles = shopMetaFiles
    .map((f) => `data_file 'SHOP_PED_APPAREL_META_FILE' '${f}'`)
    .join("\n");
  let out = template
    .replace(/\{\{\s*files\s*\}\}/gu, FILES_BLOCK)
    .replace(/\{\{\s*data_files\s*\}\}/gu, dataFiles);
  // Normalize CRLF (editor paste) and ensure exactly one trailing newline.
  out = out.replace(/\r\n/gu, "\n").replace(/\s*$/u, "");
  return `${out}\n`;
}

/** Shop-meta component entry (mirror of sidecar PlanComponent subset). */
interface PlanComponent {
  slotId: number;
  localIndex: number;
}

/** Per-(part, gender) plan — mirror of sidecar BuildPlanGender. */
interface PartGenderPlan {
  gender: "male" | "female";
  pedName: string;
  genderLetter: "m" | "f";
  /** Addon components ordered by (slotId asc, localIndex asc). */
  components: PlanComponent[];
  /**
   * Whether the desktop build emits mp_creaturemetadata_<g>_<dlc>.ymt for
   * this gender (mirror of CreatureMetadataGenerator: feet components with
   * highHeels or p_head props with a hairScaleValue).
   */
  hasCreature: boolean;
}

interface PlannedEntry {
  drawable: RevisionDrawable;
  /** Derived drawableId: (part, gender, slot) index — or replaceTargetId. */
  nnn: number;
}

interface ResourcePart {
  /** Resource folder name incl. _partN suffix when split. */
  folder: string;
  /** dlcName incl. _partN suffix when split. */
  dlc: string;
  /** Addon drawables of this part (male chunk first, then female). */
  entries: PlannedEntry[];
  /** Replace-mode overrides (part 1 only), streamed without a dlc prefix. */
  replaces: PlannedEntry[];
  /** Genders that have addon drawables in this part (male first). */
  genders: PartGenderPlan[];
}

/**
 * Split drawables into resource parts and derive per-part stream numbers —
 * mirror of sidecar BuildPlanner.Plan (see SPLIT SEMANTICS in the header).
 * `drawables` must already be filtered to entries with a YDD.
 */
export function planResourceParts(
  drawables: RevisionDrawable[],
  resourceName: string,
  dlcName: string,
  splitAt: number,
  warnings: string[],
): ResourcePart[] {
  const addons = drawables.filter((d) => d.mode !== "replace");
  const replaces = drawables.filter((d) => {
    if (d.mode !== "replace") return false;
    if (d.replaceTargetId == null) {
      warnings.push(`Replace-Drawable "${d.label || d.id}" hat kein replaceTargetId und wurde uebersprungen.`);
      return false;
    }
    return true;
  });

  const chunksOf = (list: RevisionDrawable[]): RevisionDrawable[][] => {
    const chunks: RevisionDrawable[][] = [];
    for (let i = 0; i < list.length; i += splitAt) chunks.push(list.slice(i, i + splitAt));
    return chunks;
  };
  const chunksByGender = {
    male: chunksOf(addons.filter((d) => d.gender === "male")),
    female: chunksOf(addons.filter((d) => d.gender === "female")),
  };
  const partCount = Math.max(1, chunksByGender.male.length, chunksByGender.female.length);

  const parts: ResourcePart[] = [];
  for (let partIndex = 0; partIndex < partCount; partIndex++) {
    const suffix = partCount > 1 ? `_part${partIndex + 1}` : "";
    const entries: PlannedEntry[] = [];
    const genders: PartGenderPlan[] = [];

    for (const gender of ["male", "female"] as const) {
      const chunk = chunksByGender[gender][partIndex] ?? [];
      if (chunk.length === 0) continue;

      const localIndexBySlot = new Map<string, number>();
      const components: PlanComponent[] = [];
      let hasCreature = false;
      for (const d of chunk) {
        const localIndex = localIndexBySlot.get(d.type) ?? 0;
        localIndexBySlot.set(d.type, localIndex + 1);
        entries.push({ drawable: d, nnn: localIndex });

        if (d.kind === "component") {
          components.push({ slotId: COMPONENT_IDS[d.type] ?? 0, localIndex });
          if (d.type === "feet" && d.flags.highHeels) hasCreature = true;
        } else if (d.type === "p_head" && d.flags.hairScaleValue != null) {
          hasCreature = true;
        }
      }
      components.sort((a, b) => a.slotId - b.slotId || a.localIndex - b.localIndex);
      genders.push({
        gender,
        pedName: pedName(gender),
        genderLetter: genderLetter(gender),
        components,
        hasCreature,
      });
    }

    const replaceEntries: PlannedEntry[] =
      partIndex === 0 ? replaces.map((d) => ({ drawable: d, nnn: d.replaceTargetId! })) : [];

    parts.push({
      folder: `${resourceName}${suffix}`,
      dlc: `${dlcName}${suffix}`,
      entries,
      replaces: replaceEntries,
      genders,
    });
  }
  return parts;
}

/**
 * shop_ped_apparel*.meta — byte-identical mirror of sidecar
 * ShopMetaGenerator.Build: one document per (part, gender), components only
 * (props are registered via the YMT/anchor data, pedProps stays empty),
 * ordered by (slotId, localIndex).
 */
function buildShopPedApparelMetaXml(plan: PartGenderPlan, dlc: string): string {
  const eCharacter = plan.gender === "female" ? "SCR_CHAR_MULTIPLAYER_F" : "SCR_CHAR_MULTIPLAYER";
  const creatureMeta = plan.hasCreature ? `mp_creaturemetadata_${plan.genderLetter}_${dlc}` : null;

  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push("<ShopPedApparel>");
  lines.push(`  <pedName>${xmlEscape(plan.pedName)}</pedName>`);
  lines.push(`  <dlcName>${xmlEscape(dlc)}</dlcName>`);
  lines.push(`  <fullDlcName>${xmlEscape(`${plan.pedName}_${dlc}`)}</fullDlcName>`);
  lines.push(`  <eCharacter>${eCharacter}</eCharacter>`);
  lines.push(
    creatureMeta === null
      ? "  <creatureMetaData />"
      : `  <creatureMetaData>${xmlEscape(creatureMeta)}</creatureMetaData>`,
  );
  lines.push("  <pedOutfits />");

  if (plan.components.length === 0) {
    lines.push("  <pedComponents />");
  } else {
    lines.push("  <pedComponents>");
    plan.components.forEach((component, i) => {
      const unique = `${dlc}_${plan.genderLetter}_C${component.slotId}_D${component.localIndex}_I${i}`.toUpperCase();
      lines.push("    <Item>");
      lines.push("      <lockHash>0x00000000</lockHash>");
      lines.push('      <cost value="0" />');
      lines.push("      <textLabel />");
      lines.push(`      <uniqueNameHash>${xmlEscape(unique)}</uniqueNameHash>`);
      lines.push("      <eShopEnum>SHOP_PED_APPAREL</eShopEnum>");
      lines.push(`      <drawableIndex value="${component.localIndex}" />`);
      lines.push('      <textureIndex value="0" />');
      lines.push(`      <eCompType>${COMP_NATIVE_NAMES[component.slotId]}</eCompType>`);
      lines.push("      <restrictionTags />");
      lines.push("    </Item>");
    });
    lines.push("  </pedComponents>");
  }

  lines.push("  <pedProps />");
  lines.push("</ShopPedApparel>");
  return `${lines.join("\n")}\n`;
}

/** German user-facing note shipped INSIDE every resource (stream/ATELIER_README.txt). */
function buildStreamReadme(opts: { dlc: string; genders: PartGenderPlan[] }): string {
  const ymtNames = opts.genders.map((g) => `${g.pedName}_${opts.dlc}.ymt`);
  const creatureNames = opts.genders
    .filter((g) => g.hasCreature)
    .map((g) => `mp_creaturemetadata_${g.genderLetter}_${opts.dlc}.ymt`);
  const missing = [...ymtNames, ...creatureNames];
  if (missing.length === 0) {
    return `atelier by feelgood — Server-Build

Dieses Resource-Part enthaelt nur Replace-Drawables (Basisspiel-Overrides);
es braucht keine YMT-Dateien und ist vollstaendig.
`;
  }
  return `atelier by feelgood — Server-Build (unvollstaendig!)

WICHTIG: Diesem Build fehlen die binaeren YMT-Dateien:
${missing.map((n) => `  - ${n}`).join("\n")}

Die echten CPedVariationInfo-YMTs koennen nur vom Desktop-Build der
atelier-App erzeugt werden (CodeWalker/.NET). Ohne sie laedt das Spiel
die Drawables NICHT — dieser Server-Build dient der Vorschau/Verteilung.

So bekommst du den vollstaendigen Build:
  1. Pack in der atelier-Desktop-App oeffnen (Cloud-Sync).
  2. Build-Ziel "FiveM" waehlen und lokal bauen.
  3. Der Desktop-Build enthaelt identische Stream-Dateinamen plus die YMTs.

atelier-build.json traegt "ymt": "missing-server-build" als Marker.
`;
}

/**
 * Build the full FiveM resource ZIP (one or more <resourceName>[_partN]/
 * folders) for a revision's drawables. Missing CAS assets are skipped with a
 * German warning instead of failing the whole build.
 */
export async function buildFivemResourceZip(
  drawables: RevisionDrawable[],
  readAsset: CasAssetReader,
  options: FivemBuildOptions,
): Promise<{ zip: Buffer; report: FivemBuildReport }> {
  const dlcName = sanitizeDlcName(options.dlcName);
  const resourceName = sanitizeResourceName(options.resourceName);
  const generateShopMeta = options.generateShopMeta ?? true;
  const splitAt = options.splitAt ?? DEFAULT_SPLIT_AT;

  const warnings: string[] = [];
  const usable = drawables.filter((d) => {
    if (d.ydd) return true;
    warnings.push(`Drawable "${d.label || d.id}" hat keine YDD-Datei und wurde uebersprungen.`);
    return false;
  });

  const parts = planResourceParts(usable, resourceName, dlcName, splitAt, warnings);
  const zip = new JSZip();
  const resources: FivemBuildReport["resources"] = [];

  for (const part of parts) {
    const root = zip.folder(part.folder);
    const stream = root?.folder("stream");
    if (!root || !stream) continue;

    let written = 0;

    const writeEntry = async ({ drawable: d, nnn }: PlannedEntry, dlc: string | null): Promise<void> => {
      const yddBytes = d.ydd ? await readAsset(d.ydd.sha256) : null;
      if (!yddBytes) {
        warnings.push(`Asset fuer Drawable "${d.label || d.id}" fehlt im Storage (YDD) — uebersprungen.`);
        return;
      }
      stream.file(`${drawableStreamBase(d, dlc, nnn)}.ydd`, yddBytes);
      written++;

      for (let i = 0; i < d.textures.length; i++) {
        const tex = d.textures[i]!;
        const texBytes = await readAsset(tex.sha256);
        if (!texBytes) {
          warnings.push(`Textur ${textureLetter(i)} von "${d.label || d.id}" fehlt im Storage — uebersprungen.`);
          continue;
        }
        stream.file(textureStreamName(d, dlc, nnn, i), texBytes);
      }

      // Cloth physics only exists for components (mirror of the sidecar plan).
      if (d.physics && d.kind === "component") {
        const yldBytes = await readAsset(d.physics.sha256);
        if (yldBytes) {
          stream.file(physicsStreamName(d, dlc, nnn), yldBytes);
        } else {
          warnings.push(`Physik-Datei (YLD) von "${d.label || d.id}" fehlt im Storage — uebersprungen.`);
        }
      }

      if (d.firstPerson) {
        // First-person variants are a desktop-build concern (YMT wiring) — not shipped here.
        warnings.push(`First-Person-Modell von "${d.label || d.id}" wird im Server-Build nicht exportiert.`);
      }
    };

    for (const entry of part.entries) await writeEntry(entry, part.dlc);
    for (const entry of part.replaces) await writeEntry(entry, null);

    // Shop metas mirror the sidecar: contract name for a single gender,
    // per-gender suffix when the part carries both (one XML per ped).
    const shopMetaFiles: string[] = [];
    if (generateShopMeta) {
      for (const plan of part.genders) {
        const metaName = part.genders.length === 1
          ? "shop_ped_apparel.meta"
          : `shop_ped_apparel_${plan.genderLetter}.meta`;
        stream.file(metaName, buildShopPedApparelMetaXml(plan, part.dlc));
        shopMetaFiles.push(`stream/${metaName}`);
      }
    }

    // SERVER BUILD LIMITATION marker — see file header. No fake .ymt bytes
    // are written (a corrupt YMT would crash the game); instead the gap is
    // documented in-band for whoever unpacks the artifact.
    stream.file("ATELIER_README.txt", buildStreamReadme({ dlc: part.dlc, genders: part.genders }));

    root.file(
      "fxmanifest.lua",
      options.fxmanifestTemplate
        ? renderFxmanifestTemplate(options.fxmanifestTemplate, shopMetaFiles)
        : buildFxmanifest(shopMetaFiles),
    );
    root.file(
      "atelier-build.json",
      JSON.stringify(
        {
          builtAt: new Date().toISOString(),
          target: "fivem",
          dlcName: part.dlc,
          drawables: written,
          tool: "atelier by feelgood",
          ymt: "missing-server-build",
        },
        null,
        2,
      ),
    );

    resources.push({ folder: part.folder, drawables: written });
  }

  const zipBuf = Buffer.from(await zip.generateAsync({ type: "arraybuffer", compression: "DEFLATE" }));
  return { zip: zipBuf, report: { resources, warnings } };
}
